version: '3'

services:
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      # --- Inizio Configurazione KRaft ---
      - KAFKA_CFG_PROCESS_ROLES=broker,controller

      # La riga mancante. Stiamo dicendo a Kafka che il listener chiamato 'CONTROLLER'
      # è quello usato per il ruolo di controller.
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER # <-- ECCO LA RIGA MANCANTE

      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
      # --- Fine Configurazione KRaft ---